### ISSUE TITLE
If all injections are optional, you can shorten code by puttind defaultInjectionStrategy attr in @Model annotation

### ISSUE THREAD

**Issue by SashaMikhailau** [yury-raichonok/aem-restaurant#3]
https://github.com/yury-raichonok/aem-restaurant/blob/fb4dcebc33a7bbe3067a13540fbbdc29a27c6bd2/core/src/main/java/com/restaurant/core/models/DishListModel.java#L22

**Comment by yury-raichonok** [comment]
Added defaultInjectionStrategy into @Model annotation instead of @Inject and @ValueMapValue annotations parameter
