### ISSUE TITLE
Will = work here instead of contains?

### ISSUE THREAD

**Issue by SashaMikhailau** [yury-raichonok/aem-restaurant#4]
https://github.com/yury-raichonok/aem-restaurant/blob/fb4dcebc33a7bbe3067a13540fbbdc29a27c6bd2/core/src/main/java/com/restaurant/core/services/impl/DataServiceImpl.java#L89

**Comment by yury-raichonok** [comment]
Yes. Query changed to "SELECT * FROM [nt:base] AS m WHERE ISDESCENDANTNODE ([%s]) AND m.[strCategory] = \"%s\""
