### ISSUE TITLE
Redundant usage of optional because you don`t do any filter or map operations. Is is longer then responsiveGridNode != null

### ISSUE THREAD

**Issue by SashaMikhailau** [yury-raichonok/aem-restaurant#6]
https://github.com/yury-raichonok/aem-restaurant/blob/fb4dcebc33a7bbe3067a13540fbbdc29a27c6bd2/core/src/main/java/com/restaurant/core/services/impl/PagesServiceImpl.java#L76

**Comment by yury-raichonok** [comment]
Optional.isPresent() check changed to != null
