### ISSUE TITLE
PLease move such things to configs. Use CryptoSupport encryption for password.

### ISSUE THREAD

**Issue by SashaMikhailau** [yury-raichonok/aem-restaurant#7]
https://github.com/yury-raichonok/aem-restaurant/blob/fb4dcebc33a7bbe3067a13540fbbdc29a27c6bd2/core/src/main/java/com/restaurant/core/services/impl/EmailServiceImpl.java#L26

http://www.sgaemsolutions.com/2019/12/cryptosupport-in-aem-65.html

**Comment by SashaMikhailau** [comment]
Follow the link to see how to use AEM cryptosupport.

**Comment by yury-raichonok** [comment]
Email and password are encrypted and moved to OSGi config
